add schema #16
olegdavimuka/proj-pb14-course-project-group-1 pull request #30
Opened 2023-11-23 14:40 UTC by ProkhorenkoAlina

Додала файл зі схемою даних

2023-11-23 15:16 UTC, olegdavimuka requested changes

2023-11-23 15:16 UTC, olegdavimuka commented on app/schemas/schema.py
> +from datetime import datetime
рознеси схеми по окремим файлам - user.py, goals.py і так далі
UserStatus винеси в папку constants

також аналогічно рознеси моделі в папці models по різним файлам

2023-11-24 13:13 UTC, ProkhorenkoAlina commented
@olegdavimuka, оновила гілку

2023-11-24 15:24 UTC, olegdavimuka approved these changes

2023-11-24 15:24 UTC, merged

2023-11-30 14:12 UTC, OlenaBabychUkr commented
привіт, працюю над заповненням таблиці user. Є кілька ідей. @ProkhorenkoAlina @olegdavimuka @DmitryiObukhov 

1) поле user_age буде застарівати з часом. Якщо нам дійсно потрібен вік, то може запитати рік народження і вирахувати вік. Або ще записувати коли аккаунт створений і раз на рік користувачам, які зареєструвалися не у поточному році додавати +1 рік (але якусь частину року інформація про вік буде неправдива)

2) як підтримувати унікальність користувачів? у нас є поле ід, але ніщо не спиняє мене зараєструватися 10 разів. Оскільки це чатбот прожектора, можливо у учасників вже є якийсь ідентифікатор (номер телефону, пошта), який можна використовувати і тут. Телеграм сам по собі вже використовує номер (правильно ж?)
Це також буде актуальне для прав зміни даних (щоб я не міняла чужі дані)