GitHub actions
olegdavimuka/proj-pb14-course-project-group-1 pull request #35
Opened 2023-11-24 14:24 UTC by DmitryiObukhov

2023-11-24 15:06 UTC, ProkhorenkoAlina commented on .github/workflows/github-actions.yml
> +        python-version: 3.10
перевір, можливо тут має бути string значення?

2023-11-24 15:08 UTC, ProkhorenkoAlina commented on job1.yml
видали, будь ласка, цей файл він більше не потрібен

2023-11-24 15:29 UTC, olegdavimuka requested changes

2023-11-24 15:29 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +      uses: actions/checkout@v2
change to v4

2023-11-24 15:29 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +      uses: actions/setup-python@v2
change to v4

2023-11-24 15:29 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +        python-version: 3.10
так, string, хоча можливо буде і так працювати, не впевнений

2023-11-24 15:29 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +      run: black --check .
краще black --check app, щоб перевіряти лише папку app, в якій код. Хоча, залежно від структури проекту, якщо потрібно перевіряти і інші папки та файли тоді ок

2023-11-24 15:29 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +    - name: Install pre-commit hooks
Який зміст в запуску pre-commit?

2023-11-25 17:13 UTC, olegdavimuka requested changes

2023-11-25 17:13 UTC, olegdavimuka commented on .github/workflows/github-actions.yml
> +name: Code Quality
https://github.com/olegdavimuka/proj-pb14-course-project-group-1/actions
Ось тут ти можеш подивитись всі запуски workflow, як бачиш він не проходить, в ньому є помилки, виправи їх

2023-11-29 11:14 UTC, merged